spring:
  application:
    name: app
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: development
  
server:
  address: 0.0.0.0
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    path: /index.html
  api-docs:
    path: /api-docs