spring:
  datasource:
    url: jdbc:postgresql://postgres_url_check_user:ShYjfEjXliEFE4CeCU8ghxnEYLIZtnAF@dpg-cre7q5rgbbvc73bojrpg-a.singapore-postgres.render.com/postgres_url_check
    username: postgres_url_check_user
    password: ShYjfEjXliEFE4CeCU8ghxnEYLIZtnAF
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect